messages:
  noperm-message: §cyou don't have permission
  reason-message: §cwrite a reason
  report-send-message: §6report message send
  empty-list-message: §creport list is empty
  list-message: grief list
  report-delete-message: §areport delete from list
  incorrect-id-message: §cincorrect grief ID
  clear-list-message: §areport list has been cleared
  incorrect-command-message: §cincorrect command
list-info:
  sender: sender
  details: details
  teleport: [TELEPORT]
  click-message: click to teleport