name: GriefReportPlugin
version: '${project.version}'
main: r4mblerplugins.griefreportplugin.GriefReportPlugin
api-version: 1.18
authors: [ R4mBLe_ ]
description: simply plugin for admins and moderators minecraft servers
commands:
  report:
    aliases: [report]
  reports:
    aliases: [reports]
    usage: /<command> [reason]

permissions:
  GriefPluginAllPerm.*:
    description: all permission on plugin
    children:
      GriefReportPlugin.SendReport: true
      GriefReportPlugin.ReportsManage: true

  GriefReportPlugin.SendReport:
    description: add report to reports
    default: true
  GriefReportPlugin.ReportsManage:
    description: open and manage reports(for admins, moderators, helpers)
    default: op