name: GriefReportPlugin
version: '${project.version}'
main: r4mblerplugins.griefreportplugin.GriefReportPlugin
api-version: 1.18
authors: [ R4mBLe_ ]
description: simply plugin for admins and moderators minecraft servers
commands:
  grief:
    aliases: [g, grief, griefing]
  grieflist:
    aliases: [glist, grieflist, listgrief]
    usage: /<command> [reason]

permissions:
  GriefPluginAllPerm.*:
    description: all permission on plugin
    children:
      GriefReportPlugin.SendGriefMessage: true
      GriefReportPlugin.GriefListManage: true

  GriefReportPlugin.SendGriefMessage:
    description: add grief to grief list
    default: true
  GriefReportPlugin.GriefListManage:
    description: open and manage grief list(for admins, moderators, helpers)
    default: op